version: '3.7'

services:
  searchd:
    image: manticoresearch/manticore:dev-7.4.7-39a6f50
    environment:
      EXTRA: 1
      searchd_threads: 8
    ports:
      - "9308:9308"
    logging:
      driver: "json-file"
      options:
        max-file: 1
        max-size: 10m
    deploy:
      resources:
        limits:
          memory: 25Gb
          cpus: "1.0"
